package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-09-24T13:06:27.977+02:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "PersonaSoapImplService", 
                  wsdlLocation = "http://localhost:8090/Persona/service/PersonaSoap?wsdl",
                  targetNamespace = "http://webservice/") 
public class PersonaSoapImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "PersonaSoapImplService");
    public final static QName PersonaSoapImplPort = new QName("http://webservice/", "PersonaSoapImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/Persona/service/PersonaSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonaSoapImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/Persona/service/PersonaSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonaSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonaSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaSoapImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonaSoapImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonaSoapImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonaSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PersonaSoap
     */
    @WebEndpoint(name = "PersonaSoapImplPort")
    public PersonaSoap getPersonaSoapImplPort() {
        return super.getPort(PersonaSoapImplPort, PersonaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaSoap
     */
    @WebEndpoint(name = "PersonaSoapImplPort")
    public PersonaSoap getPersonaSoapImplPort(WebServiceFeature... features) {
        return super.getPort(PersonaSoapImplPort, PersonaSoap.class, features);
    }

}
