package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-09-23T13:39:57.567+02:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "CalculadoraSoapImplService", 
                  wsdlLocation = "http://localhost:8090/Ejercicio1/service/CalculadoraSoap?wsdl",
                  targetNamespace = "http://webservice/") 
public class CalculadoraSoapImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "CalculadoraSoapImplService");
    public final static QName CalculadoraSoapImplPort = new QName("http://webservice/", "CalculadoraSoapImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/Ejercicio1/service/CalculadoraSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraSoapImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/Ejercicio1/service/CalculadoraSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraSoapImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculadoraSoapImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculadoraSoapImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculadoraSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns CalculadoraSoap
     */
    @WebEndpoint(name = "CalculadoraSoapImplPort")
    public CalculadoraSoap getCalculadoraSoapImplPort() {
        return super.getPort(CalculadoraSoapImplPort, CalculadoraSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraSoap
     */
    @WebEndpoint(name = "CalculadoraSoapImplPort")
    public CalculadoraSoap getCalculadoraSoapImplPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraSoapImplPort, CalculadoraSoap.class, features);
    }

}
