package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-09-23T10:51:31.770+02:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "HolaMundoSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HolaMundoSoap {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saludar", targetNamespace = "http://webservice/", className = "webservice.Saludar")
    @WebMethod
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://webservice/", className = "webservice.SaludarResponse")
    public java.lang.String saludar(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
